const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const state={page:'home',tab:'faq',category:'All',query:'',lang:localStorage.getItem('eh_lang')||'en',lesson:null};
const pages=[['home','⌂','Home'],['questions','?','Questions & Notes'],['rawan','R','Rawan AI'],['grammar','G','Grammar Lab'],['vocab','V','Vocabulary Lab'],['reading','R','Reading & Paragraphs'],['listening','L','Listening Lab'],['different','≠','The Different'],['idioms','I','Idioms Lab'],['sound','S','Sound Lab'],['test','✓','Self Test'],['weak','◎','Weak Point'],['presentation','P','Presentation Lab']];
const faq=[
{id:'f1',cat:'Grammar',q:'When do I use Present Simple?',ex:'Use it for habits, routines, facts, and things that are generally true.',pattern:'Subject + base verb (add -s/-es with he, she, it).',examples:['I study English every day.','She works at a hospital.'],ar:'نستخدمه للعادات والحقائق والأشياء المتكررة أو الصحيحة بشكل عام.',mistake:'❌ She work every day.  ✅ She works every day.',tip:'If it happens regularly, Present Simple is often a good first choice.',related:'Grammar Lab'},
{id:'f2',cat:'Grammar',q:'Why do we use “did” in this question?',ex:'“Did” carries the Past Simple tense, so the main verb returns to its base form.',pattern:'Did + subject + base verb ...?',examples:['Did you go yesterday?','Did she finish the homework?'],ar:'did تحمل معنى الماضي، لذلك الفعل الأساسي يرجع للمصدر.',mistake:'❌ Did you went?  ✅ Did you go?',tip:'One past marker is enough.',related:'Grammar Lab'},
{id:'f3',cat:'The Different',q:'What is the difference between “since” and “for”?',ex:'Use “since” with a starting point and “for” with a duration.',pattern:'since + point • for + period',examples:['since 2022','for four years'],ar:'since مع نقطة بداية، وfor مع مدة زمنية.',mistake:'❌ for 2022  ❌ since four years',tip:'Since = start. For = length.',related:'The Different'},
{id:'f4',cat:'Vocabulary',q:'How can I remember new vocabulary?',ex:'Learn words in context and review them over spaced intervals.',examples:['achieve a goal → She achieved her goal.'],ar:'تعلم الكلمة داخل جملة وسياق ثم راجعها على فترات.',tip:'Save one useful sentence with each important word.',related:'Vocabulary Lab'},
{id:'f5',cat:'Listening',q:'Why can I read English but struggle to hear it?',ex:'Natural speech connects, weakens, and sometimes drops sounds, while written words stay visible.',examples:['Listen → transcript → listen again.'],ar:'الكلام الطبيعي سريع وتندمج فيه الأصوات.',tip:'Practice with short clips and repeat them.',related:'Listening Lab'}];
const notes=[
{id:'n1',cat:'Grammar',title:'Understand the use before memorizing the rule',idea:'A form is easier to remember when you know what meaning it expresses.',why:'You choose the tense from the situation, not a memorized formula.',example:'I study = routine; I am studying = around now.',tip:'Ask: what does the speaker mean?',related:'Grammar Lab'},
{id:'n2',cat:'Vocabulary',title:'Do not learn a word alone',idea:'Learn a word with a natural sentence or collocation.',why:'Context makes meaning and usage easier to recall.',example:'make a decision • heavy rain • achieve a goal',tip:'Save one sentence with every new word.',related:'Vocabulary Lab'},
{id:'n3',cat:'Listening',title:'Listen for the idea before every word',idea:'First understand the message; do not translate every sound.',why:'Word-by-word translation overloads attention.',example:'First listen: topic. Second: details.',tip:'Repeat short audio with a clear purpose.',related:'Listening Lab'}];
const cats=['All','Grammar','Vocabulary','The Different','Idioms','Listening','Reading','Sound & Pronunciation','Presentation','Tests & Practice'];
const grammarLessons=[
{title:'Be + Subject Pronouns',level:'Beginner',desc:'Use am, is and are with I, you, he, she, it, we and they.',intro:'The verb be describes identity, condition, age and location.',formula:'I + am • he/she/it + is • you/we/they + are',examples:['I am a student.','She is tired.','They are at home.'],mistake:'He are happy → He is happy.',q:'Choose the correct sentence.',opts:['She are ready.','She is ready.','She am ready.'],ans:1,hint:'She uses the singular form of be.'},
{title:'A / An',level:'Beginner',desc:'Choose the correct indefinite article by sound.',intro:'Use a/an before one non-specific singular countable noun.',formula:'a + consonant sound • an + vowel sound',examples:['a university','an apple','an hour'],mistake:'an university → a university (starts with /j/ sound).',q:'Choose the correct phrase.',opts:['a apple','an apple','an university'],ans:1,hint:'Listen to the first sound, not only the first letter.'},
{title:'Present Simple vs Present Continuous',level:'Intermediate',desc:'Distinguish routines from actions happening around now.',intro:'Present Simple usually describes routines/facts; Present Continuous focuses on temporary or current activity.',formula:'I work • I am working',examples:['I study every day.','I am studying right now.'],mistake:'I am go every day → I go every day.',q:'Right now, Ali ___ for his exam.',opts:['studies','is studying','study'],ans:1,hint:'“Right now” points to an action in progress.'},
{title:'Past Simple',level:'Intermediate',desc:'Talk about completed actions in the past.',intro:'Use Past Simple for finished past events, often with a finished time.',formula:'Subject + past form',examples:['I visited my friend yesterday.','She went home early.'],mistake:'Did you went? → Did you go?',q:'Yesterday, we ___ to the library.',opts:['go','went','are going'],ans:1,hint:'The action is completed and “yesterday” is a finished time.'},
{title:'Past Continuous',level:'Intermediate',desc:'Describe an action in progress at a past time.',intro:'Past Continuous shows an activity that was in progress around a particular past moment.',formula:'was/were + verb-ing',examples:['I was studying at 8 PM.','They were playing when it rained.'],mistake:'They was playing → They were playing.',q:'At 9 PM, I ___ TV.',opts:['was watching','watched now','am watching'],ans:0,hint:'Think: activity in progress at a specific past time.'},
{title:'Countable & Uncountable + Quantifiers',level:'Intermediate',desc:'Use many, much, a few and a little accurately.',intro:'Countable nouns can be counted individually; uncountable nouns are treated as mass concepts.',formula:'many/a few + countable • much/a little + uncountable',examples:['many books','a little water'],mistake:'many water → much water.',q:'We have ___ time before class.',opts:['a little','a few','many'],ans:0,hint:'Time is uncountable in this meaning.'},
{title:'Make vs Do',level:'Intermediate',desc:'Learn common patterns instead of literal translation.',intro:'Make often focuses on creating a result; do often focuses on an activity or task.',formula:'make a decision • do homework',examples:['make a mistake','do the dishes'],mistake:'make homework → do homework.',q:'I need to ___ my homework.',opts:['make','do','making'],ans:1,hint:'Homework is a common collocation with do.'}
];
const vocab=[
{word:'achieve',type:'verb',meaning:'يحقق',example:'She achieved her goal.',coll:'achieve a goal / result',syn:'accomplish'},
{word:'confident',type:'adjective',meaning:'واثق',example:'He feels confident before the presentation.',coll:'feel confident / confident about',syn:'self-assured'},
{word:'improve',type:'verb',meaning:'يحسّن / يتحسن',example:'Practice can improve your listening.',coll:'improve skills / improve gradually',syn:'develop'},
{word:'reliable',type:'adjective',meaning:'موثوق',example:'Use a reliable source.',coll:'reliable source / reliable person',syn:'dependable'},
{word:'challenge',type:'noun / verb',meaning:'تحدٍ / يتحدى',example:'This exercise is a useful challenge.',coll:'face a challenge',syn:'difficulty'}];
const reading={title:'How Technology Changes Learning',level:'Intermediate',text:['Technology has changed the way many students learn. Digital tools can give learners quick access to explanations, examples, and practice activities. However, having more information does not automatically mean better learning.','Students still need to think, ask questions, review mistakes, and practice actively. A useful tool supports these habits instead of replacing them. The best results often come when technology and good study methods work together.'],qs:[{q:'What is the main idea?',opts:['Technology always makes learning easy.','Technology helps most when combined with active study habits.','Students should stop using books.'],ans:1},{q:'According to the text, what should students review?',opts:['Mistakes','Only vocabulary','Device settings'],ans:0}]};
const listeningItems=[{title:'Daily Routine',text:'I usually start studying at seven in the evening, but today I am starting later because I have a family visit.',q:'Why is the speaker starting later today?',opts:['Because of a family visit','Because class was cancelled','Because it is morning'],ans:0},{title:'Study Plan',text:'First, review the rule. Then try two examples without looking at the answer.',q:'What should the learner do after reviewing the rule?',opts:['Stop studying','Try two examples','Translate every word'],ans:1}];
const differences=[['say vs tell','say + something • tell + someone + something','She said hello. / She told me the truth.'],['make vs do','make = create/result • do = task/activity','make a plan / do homework'],['since vs for','since = starting point • for = duration','since Monday / for two days'],['job vs work','job is usually countable; work is usually uncountable','a new job / a lot of work']];
const idioms=[['break the ice','make people feel more comfortable at the beginning','A simple game helped break the ice.'],['under the weather','feeling slightly ill','I’m a bit under the weather today.'],['piece of cake','very easy (informal)','The first exercise was a piece of cake.']];
const sounds=[['/p/','voiceless','pen, map','Close the lips, release air; no vocal-fold vibration.'],['/b/','voiced','book, cab','Same lip movement as /p/, but with voice.'],['/θ/','voiceless','think, bath','Place the tongue lightly between the teeth and let air pass.'],['/ð/','voiced','this, mother','Similar to /θ/ but with vocal-fold vibration.'],['/ɪ/','vowel','sit, live','A short relaxed vowel.'],['/iː/','vowel','see, green','A longer vowel, usually tenser than /ɪ/.']];
const presentationIdeas=[['How Artificial Intelligence Is Changing Education','كيف يغيّر الذكاء الاصطناعي التعليم','Intermediate',['What AI tools can do','Benefits for students','Risks and responsible use']],['Why Sleep Is Important for Learning','لماذا النوم مهم للتعلم','Beginner',['Memory','Focus','Healthy study habits']],['The History of the Internet','تاريخ الإنترنت','Intermediate',['Early networks','The web','How communication changed']],['How Space Exploration May Change the Future','كيف قد يغيّر استكشاف الفضاء المستقبل','Advanced',['Science','Technology','Future missions']]];
function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function saved(){return JSON.parse(localStorage.getItem('eh_saved')||'[]')} function recent(){return JSON.parse(localStorage.getItem('eh_recent')||'[]')}
function progress(){return JSON.parse(localStorage.getItem('eh_progress')||'{}')} function setProgress(k,v){let p=progress();p[k]=v;localStorage.setItem('eh_progress',JSON.stringify(p))}
function brand(){return `<div class="brand"><img class="brand-logo" src="assets/english-hub-logo.png" alt="English HUB logo"><div>English HUB<br><small class="muted">Learn with clarity</small></div></div>`}
function topbar(){const name=localStorage.getItem('eh_name');return `<header class="topbar"><div><b>${pages.find(p=>p[0]===state.page)?.[2]||'English HUB'}</b></div><div class="top-actions"><button class="pill" id="lang">${state.lang==='en'?'العربية':'English'}</button><span class="pill">${name?`Hi, ${esc(name)}`:'Welcome'}</span></div></header>`}
function render(){const app=$('#app');app.className=state.lang==='ar'?'rtl':'';app.innerHTML=`<div class="shell"><aside class="sidebar">${brand()}<div class="nav">${pages.map(p=>`<button data-page="${p[0]}" class="${state.page===p[0]?'active':''}"><span>${p[1]}</span>${p[2]}</button>`).join('')}</div><div class="side-foot">Your progress stays on this device.<br><b>No account required.</b></div></aside><main class="main">${topbar()}<div class="content">${page()}</div></main></div><div class="mobile-nav">${pages.slice(0,3).map(p=>`<button data-page="${p[0]}" class="${state.page===p[0]?'active':''}">${p[1]}<br>${p[2].split(' ')[0]}</button>`).join('')}</div>`;bind();if(!localStorage.getItem('eh_onboarded'))onboarding(1)}
function page(){if(state.page==='home')return home();if(state.page==='questions')return questions();if(state.page==='rawan')return rawan();if(state.page==='grammar')return grammar();if(state.page==='vocab')return vocabulary();if(state.page==='reading')return readingPage();if(state.page==='listening')return listening();if(state.page==='different')return different();if(state.page==='idioms')return idiomsPage();if(state.page==='sound')return sound();if(state.page==='test')return selfTest();if(state.page==='weak')return weakPoint();if(state.page==='presentation')return presentation();return home()}
function home(){return `<section class="hero fade-up"><div class="hero-copy"><div class="eyebrow">A calmer way to learn English</div><h1>Understand it.<br>Use it. Keep it.</h1><p>Learn through clear explanations, real examples, practice, feedback, and review. Your progress is stored locally on this device.</p><div class="hero-actions"><button class="primary" data-page="grammar">Start learning</button><button class="secondary" data-page="rawan">Ask Rawan</button></div></div><div class="hero-visual"><div class="word-orbit"><span class="orb">Grammar</span><span class="orb">Listening</span><span class="orb">Vocabulary</span><span class="orb">Practice</span><div class="center-orb">Aa</div></div></div></section><div class="grid">${[['G','Grammar Lab','Learn → understand → practice → improve.','grammar'],['R','Reading & Paragraphs','Read, analyze, answer, and build better paragraphs.','reading'],['V','Vocabulary Lab','Meaning, context, collocations, sound and review.','vocab'],['🔊','Sound Lab','See, hear, compare and practice English sounds.','sound'],['✓','Self Test','Test yourself and review real mistakes.','test'],['P','Presentation Lab','Plan, organize, speak and avoid common mistakes.','presentation']].map(x=>`<article class="card"><div class="card-icon">${x[0]}</div><h3>${x[1]}</h3><p>${x[2]}</p><button class="ghost arrow" data-page="${x[3]}">Open →</button></article>`).join('')}</div>`}
function questions(){let data=state.tab==='faq'?faq:notes,q=state.query.toLowerCase().trim();data=data.filter(x=>(state.category==='All'||x.cat===state.category)&&(!q||JSON.stringify(x).toLowerCase().includes(q)));return `<div class="section-head"><div><div class="eyebrow">FAQ + Learning Notes + Quick Help</div><h2>Questions & Notes</h2></div><label class="search">⌕ <input id="search" value="${esc(state.query)}" placeholder="Search English, Arabic, topic..."></label></div><div class="tabs"><button class="tab ${state.tab==='faq'?'active':''}" data-tab="faq">FAQ</button><button class="tab ${state.tab==='notes'?'active':''}" data-tab="notes">Notes</button><button class="tab" id="savedTab">♡ Saved (${saved().length})</button></div><div class="chips">${cats.map(c=>`<button class="chip ${state.category===c?'active':''}" data-cat="${c}">${c}</button>`).join('')}</div><div class="qn-layout" style="margin-top:18px"><div class="items" id="items">${data.length?data.map(itemCard).join(''):'<div class="empty">No matching items.</div>'}</div><aside class="side-stack"><div class="mini"><h3>Quick Help</h3><div class="quick-grid">${['Grammar','Vocabulary','Listening','The Different'].map(c=>`<button data-quick="${c}">${c}</button>`).join('')}</div></div><div class="mini"><h3>Recently viewed</h3>${recent().slice(0,4).map(id=>{let x=[...faq,...notes].find(a=>a.id===id);return x?`<p>• ${esc(x.q||x.title)}</p>`:''}).join('')||'<p class="muted">Nothing yet.</p>'}</div></aside></div>`}
function itemCard(x){const f=!!x.q;return `<article class="item"><div class="item-head"><span class="tag">${x.cat}</span><button data-open="${x.id}">${esc(x.q||x.title)}</button><span>＋</span></div><div class="item-body hidden" id="body-${x.id}">${f?`<h4>Simple Explanation</h4><p>${x.ex}</p>${x.pattern?`<h4>Pattern</h4><p>${x.pattern}</p>`:''}<h4>Examples</h4>${x.examples.map(e=>`<div class="example">${e}</div>`).join('')}<h4>العربية</h4><p class="rtl">${x.ar}</p>${x.mistake?`<h4>Common Mistake</h4><div class="mistake">${x.mistake}</div>`:''}`:`<h4>The Idea</h4><p>${x.idea}</p><h4>Why it matters</h4><p>${x.why}</p><div class="example">${x.example}</div>`}<h4>Quick Tip</h4><p>💡 ${x.tip}</p><div class="save-row"><button class="secondary" data-save="${x.id}">${saved().includes(x.id)?'♥ Saved':'♡ Save'}</button><button class="secondary" data-speak="${x.id}">🔊 Listen</button><button class="primary" data-related="${x.related}">Practice → ${x.related}</button></div></div></article>`}
function sectionHero(title,sub,flow){return `<div class="section-head"><div><div class="eyebrow">${flow}</div><h2>${title}</h2><div class="muted">${sub}</div></div><button class="secondary" data-page="rawan">Ask Rawan</button></div>`}
function grammar(){if(state.lesson!==null){let x=grammarLessons[state.lesson];return `${sectionHero(x.title,x.desc,'Learn → Understand → Practice → Improve')}<button class="secondary" id="backLessons">← All Grammar Topics</button><div class="lesson-grid"><article class="lesson-panel"><span class="tag">${x.level}</span><h3>Introduction</h3><p>${x.intro}</p><h3>How the rule works</h3><div class="formula">${x.formula}</div><h3>Examples</h3>${x.examples.map(e=>`<div class="example">${e} <button class="listen-mini" data-utter="${esc(e)}">🔊</button></div>`).join('')}<h3>Important note / Common mistake</h3><div class="mistake">${x.mistake}</div></article><article class="lesson-panel"><h3>Practice</h3><p>${x.q}</p>${x.opts.map((o,i)=>`<button class="answer" data-answer="${i}">${o}</button>`).join('')}<div id="feedback" class="feedback muted">Choose an answer. You get a hint before the solution when needed.</div></article></div>`}return `${sectionHero('Grammar','Understand the rules. Use them with confidence.','Learn → Understand → Practice → Discover Mistakes → Improve')}<div class="grid">${grammarLessons.map((x,i)=>`<article class="card"><span class="tag">${x.level}</span><h3>${x.title}</h3><p>${x.desc}</p><button class="primary" data-lesson="${i}">Start learning</button></article>`).join('')}</div>`}
function vocabulary(){return `${sectionHero('Vocabulary Lab','Learn words in context, hear them, use them, and review mistakes.','Meaning → Context → Use → Practice')}<label class="search"><span>⌕</span><input id="vocabSearch" placeholder="Search a word or meaning..."></label><div class="grid" id="vocabGrid">${vocab.map(vocabCard).join('')}</div>`}
function vocabCard(x){return `<article class="card vocab-card" data-vocab="${(x.word+' '+x.meaning).toLowerCase()}"><div class="card-icon">Aa</div><h3>${x.word}</h3><span class="tag">${x.type}</span><p class="rtl"><b>${x.meaning}</b></p><div class="example">${x.example}</div><p><b>Collocation:</b> ${x.coll}</p><p><b>Related:</b> ${x.syn}</p><button class="secondary" data-utter="${x.word}. ${x.example}">🔊 Listen</button></article>`}
function readingPage(){return `${sectionHero('Reading & Paragraphs','Read → understand → analyze → practice → write → improve.','Reading + Writing')}<div class="tabs"><button class="tab active">Reading</button><button class="tab" id="paragraphHelp">Paragraph Builder</button></div><article class="lesson-panel"><span class="tag">${reading.level}</span><h2>${reading.title}</h2>${reading.text.map(p=>`<p class="reading-text">${p}</p>`).join('')}<button class="secondary" data-utter="${esc(reading.text.join(' '))}">🔊 Listen to text</button><h3>Comprehension</h3>${reading.qs.map((q,qi)=>`<div class="quiz-block"><b>${qi+1}. ${q.q}</b>${q.opts.map((o,i)=>`<button class="answer read-answer" data-q="${qi}" data-answer="${i}">${o}</button>`).join('')}<div id="rf${qi}" class="feedback muted"></div></div>`).join('')}</article>`}
function listening(){return `${sectionHero('Listening Lab','Train for meaning, details and natural speech.','Listen → Understand → Practice → Check → Improve')}<div class="grid">${listeningItems.map((x,i)=>`<article class="card"><div class="card-icon">🔊</div><h3>${x.title}</h3><p>Listen first. Read the transcript only after trying.</p><button class="primary" data-utter="${esc(x.text)}">▶ Listen</button><details><summary>Transcript</summary><p>${x.text}</p></details><p><b>${x.q}</b></p>${x.opts.map((o,j)=>`<button class="answer listen-answer" data-q="${i}" data-answer="${j}">${o}</button>`).join('')}<div id="lf${i}" class="feedback muted"></div></article>`).join('')}</div>`}
function different(){return `${sectionHero('The Different','Similar doesn’t mean the same. Learn the difference. Use the right word.','Compare → Understand → Apply')}<div class="grid">${differences.map(x=>`<article class="card"><div class="card-icon">≠</div><h3>${x[0]}</h3><p>${x[1]}</p><div class="example">${x[2]}</div><button class="secondary" data-prompt="Explain ${x[0]} with examples and quiz me">Practice with Rawan</button></article>`).join('')}</div>`}
function idiomsPage(){return `${sectionHero('Idioms Lab','Understand meaning, context and natural usage — not literal translation.','Meaning → Context → Use')}<div class="grid">${idioms.map(x=>`<article class="card"><div class="card-icon">I</div><h3>${x[0]}</h3><p>${x[1]}</p><div class="example">${x[2]}</div><button class="secondary" data-utter="${esc(x[2])}">🔊 Listen</button></article>`).join('')}</div>`}
function sound(){return `${sectionHero('Sound Lab','See → understand → hear → compare → practice → test.','Pronunciation & IPA')}<div class="grid">${sounds.map(x=>`<article class="card"><div class="card-icon">${x[0]}</div><h3>${x[0]}</h3><span class="tag">${x[1]}</span><p><b>Examples:</b> ${x[2]}</p><p>${x[3]}</p><button class="secondary" data-utter="${x[2].split(',')[0]}">🔊 Listen</button></article>`).join('')}</div><article class="lesson-panel"><h3>Sound Pairs</h3><p>/p/ vs /b/ • /θ/ vs /ð/ • /ɪ/ vs /iː/</p><p class="muted">Compare voicing, mouth position and minimal-pair examples. The browser voice is for listening practice; the site does not claim to score your microphone pronunciation.</p></article>`}
function selfTest(){const pool=[{q:'She ___ to school every day.',opts:['go','goes','is go'],ans:1,topic:'Grammar'},{q:'Choose the natural collocation.',opts:['make homework','do homework','create homework'],ans:1,topic:'Vocabulary'},{q:'“since” is normally used with…',opts:['a starting point','a duration only','a plural noun'],ans:0,topic:'The Different'},{q:'Which is a clear presentation transition?',opts:['Let’s move on to…','Yesterday blue.','Very because.'],ans:0,topic:'Presentation'}];return `${sectionHero('Test Yourself','Choose → Test → Check → Understand Mistakes → Review → Retest','Quick Mixed Test')}<article class="lesson-panel"><div id="testArea">${pool.map((q,qi)=>`<div class="quiz-block"><span class="tag">${q.topic}</span><h3>${qi+1}. ${q.q}</h3>${q.opts.map((o,i)=>`<button class="answer test-answer" data-q="${qi}" data-answer="${i}">${o}</button>`).join('')}<div id="tf${qi}" class="feedback muted"></div></div>`).join('')}</div><div class="score-box" id="scoreBox">Answered: 0/${pool.length}</div></article>`}
function weakPoint(){let p=progress(), mistakes=Object.entries(p).filter(([,v])=>v&&v.wrong).sort((a,b)=>b[1].wrong-a[1].wrong);return `${sectionHero('Weak Point','Review patterns based on your actual mistakes on this device.','Discover → Review → Retest')}<article class="lesson-panel">${mistakes.length?mistakes.map(([k,v])=>`<div class="weak-row"><div><b>${esc(k)}</b><div class="muted">Mistakes recorded: ${v.wrong}</div></div><button class="secondary" data-page="${v.page||'test'}">Review</button></div>`).join(''):'<div class="empty">No repeated mistakes recorded yet. Complete practices and tests first.</div>'}</article>`}
function presentation(){return `${sectionHero('Presentation Lab','Learn how to plan, organize and deliver a presentation in English.','Plan → Organize → Speak → Practice → Improve')}<div class="grid">${[['1','Presentation Basics','Introduction → Main Points → Examples → Conclusion'],['2','How to Start','Question • Imagine • Interesting fact • Short story'],['3','Useful Phrases','First of all… • Let’s move on to… • To sum up…'],['4','Speaking Tips','Speak clearly, pause naturally, look at your audience.'],['5','Common Mistakes','Avoid reading slides word-for-word, rushing, and overloading slides.'],['6','Slides','Slides = key points. Speaker = explanation.']].map(x=>`<article class="card"><div class="card-icon">${x[0]}</div><h3>${x[1]}</h3><p>${x[2]}</p></article>`).join('')}</div><article class="lesson-panel"><h2>Presentation Ideas — أفكار للعروض</h2><div class="grid">${presentationIdeas.map((x,i)=>`<article class="card"><span class="tag">${x[2]}</span><h3>${x[0]}</h3><p class="rtl">${x[1]}</p><p>${x[3].map(a=>'• '+a).join('<br>')}</p><button class="primary" data-topic="${i}">Use This Topic</button></article>`).join('')}</div></article><article class="lesson-panel"><h3>Mini Challenge</h3><p>What is the best way to end a presentation?</p><button class="answer pres-answer" data-answer="0">Stop suddenly.</button><button class="answer pres-answer" data-answer="1">To sum up… Thank you for listening. Are there any questions?</button><div id="pf" class="feedback muted"></div></article>`}
function rawan(){return `<div class="rawan"><aside class="rawan-side"><div class="rawan-avatar"><img src="assets/rawan-logo.png" alt="Rawan logo"></div><h2>Rawan</h2><p class="muted">English specialist & learning assistant.</p><div class="status" id="rawanStatus"><span class="dot"></span>CHECKING...</div><div class="suggestions"><button data-prompt="Explain Present Perfect simply">Explain something</button><button data-prompt="Quiz me on Present Simple">Quiz me</button><button data-prompt="Correct: She go to school every day">Correct my sentence</button><button data-prompt="Give me a hint for: She ___ to school every day">Give me a hint</button></div><button class="secondary" id="guide" style="margin-top:18px;width:100%">📖 دليل استخدام روان</button></aside><section class="chat"><div class="chat-head"><div><b>Rawan | روان</b><div class="status"><span class="dot"></span>English learning assistant</div></div><button class="secondary" id="full">⛶ Full Screen</button></div><div class="messages" id="messages"></div><form class="composer" id="chatForm"><input id="chatInput" autocomplete="off" placeholder="Ask Rawan anything about English..."><button class="primary">Send</button></form></section></div>`}
function addRecent(id){let a=recent().filter(x=>x!==id);a.unshift(id);localStorage.setItem('eh_recent',JSON.stringify(a.slice(0,6)))}
function speak(text, slow = false) {
  // Check browser support
  if (
    !("speechSynthesis" in window) ||
    !("SpeechSynthesisUtterance" in window)
  ) {
    alert("Your browser does not support text-to-speech.");
    return;
  }

  // Stop any voice that is already playing
  window.speechSynthesis.cancel();

  const utterance = new SpeechSynthesisUtterance(text);

  // English pronunciation
  utterance.lang = "en-US";

  // Clear learning-friendly speed
  utterance.rate = slow ? 0.65 : 0.85;

  // Natural pitch
  utterance.pitch = 1;

  // Full volume
  utterance.volume = 1;

  // Get available voices
  const voices = window.speechSynthesis.getVoices();

  // Try to choose a good English voice
  const preferredVoice =
    // Microsoft voices
    voices.find(
      (voice) =>
        voice.lang === "en-US" &&
        /Aria|Jenny|Guy|Andrew|Emma|Brian/i.test(voice.name)
    ) ||

    // Google English voice
    voices.find(
      (voice) =>
        voice.lang === "en-US" &&
        /Google US English/i.test(voice.name)
    ) ||

    // Apple / other good voices
    voices.find(
      (voice) =>
        voice.lang.startsWith("en") &&
        /Samantha|Daniel|Karen/i.test(voice.name)
    ) ||

    // Any US English voice
    voices.find(
      (voice) => voice.lang === "en-US"
    ) ||

    // Any English voice
    voices.find(
      (voice) => voice.lang.startsWith("en")
    );

  // Use the selected voice
  if (preferredVoice) {
    utterance.voice = preferredVoice;
  }

  // Handle speech errors
  utterance.onerror = function (event) {
    console.error("Speech error:", event.error);
  };

  // Play
  window.speechSynthesis.speak(utterance);
}


// Load voices correctly in Chrome / Brave / Edge
if ("speechSynthesis" in window) {
  window.speechSynthesis.getVoices();

  window.speechSynthesis.onvoiceschanged = function () {
    window.speechSynthesis.getVoices();
  };
}
function recordMistake(topic,page){let p=progress(),v=p[topic]||{wrong:0,page};v.wrong++;v.page=page;p[topic]=v;localStorage.setItem('eh_progress',JSON.stringify(p))}
function bind(){ $$('[data-page]').forEach(b=>b.onclick=()=>{state.page=b.dataset.page;state.lesson=null;render();scrollTo(0,0)});$('#lang')?.addEventListener('click',()=>{state.lang=state.lang==='en'?'ar':'en';localStorage.setItem('eh_lang',state.lang);render()});$$('[data-utter]').forEach(b=>b.onclick=()=>speak(b.dataset.utter));$$('[data-prompt]').forEach(b=>b.onclick=()=>{state.page='rawan';render();setTimeout(()=>{let i=$('#chatInput');if(i){i.value=b.dataset.prompt;i.focus()}},0)});if(state.page==='questions')bindQN();if(state.page==='rawan')bindRawan();if(state.page==='grammar')bindGrammar();if(state.page==='vocab')$('#vocabSearch')?.addEventListener('input',e=>$$('.vocab-card').forEach(c=>c.style.display=c.dataset.vocab.includes(e.target.value.toLowerCase())?'':'none'));if(state.page==='reading')bindReading();if(state.page==='listening')bindListening();if(state.page==='test')bindTest();if(state.page==='presentation')bindPresentation()}
function bindQN(){$('#search').oninput=e=>{state.query=e.target.value;render()};$$('[data-tab]').forEach(b=>b.onclick=()=>{state.tab=b.dataset.tab;state.category='All';render()});$$('[data-cat]').forEach(b=>b.onclick=()=>{state.category=b.dataset.cat;render()});$$('[data-quick]').forEach(b=>b.onclick=()=>{state.category=b.dataset.quick;render()});$$('[data-open]').forEach(b=>b.onclick=()=>{let el=$('#body-'+b.dataset.open);el.classList.toggle('hidden');addRecent(b.dataset.open)});$$('[data-save]').forEach(b=>b.onclick=()=>{let a=saved(),id=b.dataset.save;a=a.includes(id)?a.filter(x=>x!==id):[...a,id];localStorage.setItem('eh_saved',JSON.stringify(a));toast(a.includes(id)?'Saved locally':'Removed');render()});$$('[data-speak]').forEach(b=>b.onclick=()=>{let x=[...faq,...notes].find(a=>a.id===b.dataset.speak);speak(x.q||x.title)});$$('[data-related]').forEach(b=>b.onclick=()=>{const m={'Grammar Lab':'grammar','Vocabulary Lab':'vocab','Listening Lab':'listening','The Different':'different'};state.page=m[b.dataset.related]||'home';render()});$('#savedTab').onclick=()=>{let ids=saved(),items=[...faq,...notes].filter(x=>ids.includes(x.id));$('#items').innerHTML=items.length?items.map(itemCard).join(''):'<div class="empty">You have no saved items yet.</div>';}}
function bindGrammar(){$$('[data-lesson]').forEach(b=>b.onclick=()=>{state.lesson=+b.dataset.lesson;render()});$('#backLessons')?.addEventListener('click',()=>{state.lesson=null;render()});$$('[data-answer]').forEach(b=>b.onclick=()=>{let x=grammarLessons[state.lesson],ok=+b.dataset.answer===x.ans,f=$('#feedback');if(ok){f.innerHTML='✅ Correct. '+x.intro;f.className='feedback good';setProgress('Grammar: '+x.title,{wrong:progress()['Grammar: '+x.title]?.wrong||0,page:'grammar'})}else{f.innerHTML='Not quite. Hint: '+x.hint+' Try again.';f.className='feedback bad';recordMistake('Grammar: '+x.title,'grammar')}})}
function bindReading(){$$('.read-answer').forEach(b=>b.onclick=()=>{let q=reading.qs[+b.dataset.q],ok=+b.dataset.answer===q.ans,f=$('#rf'+b.dataset.q);f.textContent=ok?'✅ Correct — check the sentence in the text that supports it.':'Try again. Return to the text and look for the idea, not just a matching word.';f.className='feedback '+(ok?'good':'bad');if(!ok)recordMistake('Reading comprehension','reading')});$('#paragraphHelp')?.addEventListener('click',()=>modal('<h2>Paragraph Builder</h2><p><b>1. Topic sentence</b> — state one clear main idea.</p><p><b>2. Supporting sentences</b> — add reasons, details or examples.</p><p><b>3. Linking words</b> — First, In addition, However, For example, Finally.</p><p><b>4. Concluding sentence</b> — close the idea without copying the opening sentence word-for-word.</p><div class="example">Topic → Support → Example → Conclusion</div>'))}
function bindListening(){$$('.listen-answer').forEach(b=>b.onclick=()=>{let q=listeningItems[+b.dataset.q],ok=+b.dataset.answer===q.ans,f=$('#lf'+b.dataset.q);f.textContent=ok?'✅ Correct. You caught the key detail.':'Not yet. Listen again and focus on the reason/detail asked for.';f.className='feedback '+(ok?'good':'bad');if(!ok)recordMistake('Listening details','listening')})}
function bindTest(){const pool=[{ans:1,topic:'Grammar'},{ans:1,topic:'Vocabulary'},{ans:0,topic:'The Different'},{ans:0,topic:'Presentation'}];let answered=new Set();$$('.test-answer').forEach(b=>b.onclick=()=>{let qi=+b.dataset.q,q=pool[qi],ok=+b.dataset.answer===q.ans,f=$('#tf'+qi);f.textContent=ok?'✅ Correct':'❌ Not correct. Review this topic, then try again.';f.className='feedback '+(ok?'good':'bad');answered.add(qi);if(!ok)recordMistake(q.topic,'test');$('#scoreBox').textContent=`Answered: ${answered.size}/${pool.length}`})}
function bindPresentation(){$$('[data-topic]').forEach(b=>b.onclick=()=>{let x=presentationIdeas[+b.dataset.topic];modal(`<h2>${x[0]}</h2><p class="rtl">${x[1]}</p><h3>Suggested structure</h3><p><b>Opening:</b> Have you ever wondered how ${x[0].toLowerCase()}?</p><p><b>Main points:</b><br>${x[3].map((a,i)=>`${i+1}. ${a}`).join('<br>')}</p><p><b>Conclusion direction:</b> Summarize the key idea and explain why it matters.</p><p><b>Useful phrases:</b> First of all… • Another important point is… • To sum up…</p>`) });$$('.pres-answer').forEach(b=>b.onclick=()=>{let ok=+b.dataset.answer===1;$('#pf').textContent=ok?'✅ Correct. A clear conclusion summarizes and closes the presentation.':'Try again. A presentation should have a clear ending rather than stop suddenly.';$('#pf').className='feedback '+(ok?'good':'bad');if(!ok)recordMistake('Presentation ending','presentation')})}
function bindRawan(){const box=$('#messages');let msgs=JSON.parse(sessionStorage.getItem('rawan_msgs')||'null')||[{r:'ai',t:'أهلاً! أنا روان، مساعدتك التعليمية داخل English HUB. اسألني عن أي شيء في الإنجليزية، وإذا ما فهمت الشرح احكيلي: بسطيها.'}],busy=false;const draw=()=>{box.innerHTML=msgs.map(m=>`<div class="msg ${m.r}">${esc(m.t)}</div>`).join('')+(busy?'<div class="msg ai">روان تكتب…</div>':'');box.scrollTop=box.scrollHeight;sessionStorage.setItem('rawan_msgs',JSON.stringify(msgs))};draw();fetch('/api/status').then(r=>r.json()).then(d=>{$('#rawanStatus').innerHTML=`<span class="dot ${d.online?'':'off'}"></span>${d.online?'ONLINE':'API NOT CONFIGURED'}`}).catch(()=>{$('#rawanStatus').textContent='SERVER OFFLINE'});async function send(t){if(!t.trim()||busy)return;msgs.push({r:'user',t:t.trim()});busy=true;draw();try{const history=msgs.slice(-18).map(m=>({role:m.r==='ai'?'assistant':'user',content:m.t})),response=await fetch('/api/rawan',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({messages:history})}),data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||'API error');msgs.push({r:'ai',t:data.reply})}catch(err){msgs.push({r:'ai',t:`تعذر الاتصال بروان الآن. ${err.message||''}`})}finally{busy=false;draw()}}$('#chatForm').onsubmit=e=>{e.preventDefault();let i=$('#chatInput'),v=i.value;i.value='';send(v)};$$('[data-prompt]').forEach(b=>b.onclick=()=>send(b.dataset.prompt));$('#guide').onclick=()=>modal('<h2>دليل استخدام روان</h2><p>اسأل روان عن القواعد، الكلمات، الترجمة، الكتابة، النطق، القراءة، الاستماع، التصحيح والفروقات.</p><p><b>جرّب:</b> اشرحلي Present Perfect • اختبرني • صحح جملتي • أعطيني تلميح • بسطيها.</p>');$('#full').onclick=()=>$('.rawan').requestFullscreen?.()}
function toast(t){let d=document.createElement('div');d.className='toast';d.textContent=t;document.body.appendChild(d);setTimeout(()=>d.remove(),1800)}
function modal(html){let d=document.createElement('div');d.className='modal';d.innerHTML=`<div class="modal-card">${html}<button class="primary" id="closeModal" style="margin-top:18px">Close</button></div>`;document.body.appendChild(d);$('#closeModal',d).onclick=()=>d.remove();d.onclick=e=>{if(e.target===d)d.remove()}}
function onboarding(step){let old=$('.onboarding');old?.remove();let d=document.createElement('div');d.className='onboarding';if(step===1)d.innerHTML=`<div class="on-card center"><div class="on-icon">Aa</div><div class="eyebrow">English HUB</div><h1>Are you ready to try English Hub?</h1><p class="muted">A focused place to understand, practice and improve your English.</p><button class="primary" id="onNext">Continue</button></div>`;else if(step===2)d.innerHTML=`<div class="on-card"><h2>Your learning stays yours</h2><div class="privacy-list"><div>✓ No account, Gmail or password required.</div><div>✓ Your name is only used to personalize the experience.</div><div>✓ Progress is stored locally in this browser.</div><div>! Clearing browser data or changing devices may remove local progress.</div></div><button class="primary" id="onNext">I understand</button></div>`;else d.innerHTML=`<div class="on-card"><h2>شو بدنا نناديك؟ 🤍</h2><p class="muted">Optional — you can continue without a name.</p><input class="name-input" id="onName" placeholder="Your name"><button class="primary" id="onDone">Start English HUB</button></div>`;document.body.appendChild(d);$('#onNext',d)?.addEventListener('click',()=>onboarding(step+1));$('#onDone',d)?.addEventListener('click',()=>{let n=$('#onName',d).value.trim();if(n)localStorage.setItem('eh_name',n);localStorage.setItem('eh_onboarded','1');d.remove();render()})}
render();
